# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: '45 04 * * *'
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        
    steps:
    - name: Slack Notification
      uses: act10ns/slack@v1
      with: 
        status: starting
        channel: '#qa-automation'
        message: Test execution Starts...
        if: always()
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: | 
           Xvfb :99 -ac -screen 0 1280x1024x24 &
           export DISPLAY=:99
           google-chrome --no-sandbox &
           mvn verify
    - uses: deblockt/cucumber-report-annotations-action@v1.7
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        path: "**/cucumber.json"
    - name: Deploy report page to GitHub Page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/cucumber-report-html/cucumber-html-reports
    - name: Read package.json
      id: package
      uses: juliangruber/read-file-action@v1
      with:
        path: '/target/cucumber-reports/cucumber.json'
    - name: Echo package.json
      env:
        VERIFICATION_PURPOSE: '${{ steps.package.outputs.content }}'
      if: | 
        contains(env.VERIFICATION_PURPOSE, 'failed') ||
        contains(env.VERIFICATION_PURPOSE, 'skipped') 
      run: |
        exit 1
    - name: Slack Notification
      if: always()
      uses: act10ns/slack@v1
      with: 
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#qa-automation'    
    - name: Slack Notification Success
      if: ${{ success() }}
      uses: act10ns/slack@v1
      with: 
        status: ${{ job.status }}
        channel: '#qa-automation'
        message: All test cases are PASSED, View reports here...https://sm-automation-report.alpha.snackmagic.com
    - name: Slack Notification Failure
      if: ${{ failure() }}
      uses: act10ns/slack@v1
      with: 
        status: ${{ job.status }}
        channel: '#qa-automation'
        message: Some test cases are Failed, View reports here...https://sm-automation-report.alpha.snackmagic.com
