# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: '45 04 * * *'
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        
    steps:
    - name: Slack Notification
      uses: act10ns/slack@v1
      with: 
        status: starting
        channel: '#qa-automation'
        message: Test execution Starts...
        if: always()
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package
    - uses: deblockt/cucumber-report-annotations-action@v1.7
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        path: "**/cucumber.json"
    - name: Read package.json
      id: package
      uses: juliangruber/read-file-action@v1
      with:
        path: 'target\cucumber-reports\cucumber.json'
    - name: Echo package.json
      env:
         VERIFICATION_PURPOSE: '${{ steps.package.outputs.content }}'
      run: echo "let's run validation"
    - name: Status of test run
      if: contains(env.VERIFICATION_PURPOSE, 'passed')
      env:
        TEST_STATUS: Passed
      run: echo "Passed it"
    - name: Deploy report page to GitHub Page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/cucumber-report-html/cucumber-html-reports
    - name: Slack Notification
      if: always()
      uses: act10ns/slack@v1
      with: 
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#qa-automation'
    - name: Slack Notification
      if: always()
      uses: act10ns/slack@v1
      with: 
        status: ${{ job.status }}
        mention: 'here'
        steps: ${{ toJson(steps) }}
        channel: '#qa-automation'
        message: Status is $env.TEST_STATUS ....View reports here...https://sm-automation-report.alpha.snackmagic.com
        
        
