# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: '45 04 * * *'
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: | 
           wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_104.0.5112.48-1_amd64.deb \
           && apt install -y /tmp/chrome.deb \
           && rm /tmp/chrome.deb
           Xvfb :99 -ac -screen 0 1280x1024x24 &
           export DISPLAY=:99
           google-chrome --no-sandbox &
           mvn verify
    - uses: deblockt/cucumber-report-annotations-action@v1.7
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        path: "**/cucumber.json"
    - name: Deploy report page to GitHub Page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/cucumber-report-html/cucumber-html-reports
    - name: get number of occurances
      id: count
      run: |
        echo "PASSED_COUNT=$( grep -o -i \"passed\" /home/runner/work/november/november/target/cucumber-reports/cucumber.json | wc -l )" >> $GITHUB_ENV
        echo "TOTAL_COUNT=$( grep -o -i \"Feature\" /home/runner/work/november/november/target/cucumber-reports/cucumber.json | wc -l )" >> $GITHUB_ENV
    - name: Return values 
      if: env.PASSED_COUNT < 7
      run: echo "Jugaad is successful"
    - name: All values are
      run: | 
        echo "Failed are ${{ env.PASSED_COUNT }}"
        echo "Total scenariors are ${{ env.TOTAL_COUNT }}" 
        echo "Passed are $(( ${{env.PASSED_COUNT}} - ${{env.TOTAL_COUNT}} ))" 
